### ISSUE TITLE
Adjust permissions of /etc/ssl/private for browsersync

### ISSUE THREAD

**Issue by kellypacker** [fostermadeco/development-standard#18]
Add task to give "others" the permission to traverse `/etc/ssl/private` the directory and see the files inside it (`sudo chmod o+x`). This will allow browsersync to use  `/etc/ssl/private/{{ hostname }}.key` so it will run with a valid ssl certificate.

**Comment by likeuntomurphy** [comment]
This should be taken care of the `roles` repo with this PR: https://github.com/fostermadeco/ansible-roles/pull/34
