### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by alexmglover** [fostermadeco/development-standard#4]
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by likeuntomurphy** [comment]
This is specific to Ansible 2.4, so fixing this will also require 2.4 as a minimum version. Looks fairly easy — https://www.jeffgeerling.com/blog/2016/require-minimum-ansible-version-your-playbook

**Comment by smaida** [comment]
Repo archived. Won't fix.
