### ISSUE TITLE
"sudo: a password is required" error on "trust self-signed cert" task

### ISSUE THREAD

**Issue by alexmglover** [fostermadeco/development-standard#5]
This can be recreated by spinning up a box, then trying to re-provision.

This is the full error:

```
fatal: [default -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by likeuntomurphy** [comment]
I think this will need to be split into two steps — fetching the cert from the guest to the host can stay in the Ansible certificate task, but trusting the cert will need to be moved into the Vagrantfile. We'll probably want to add the vagrant hooks plugin to master (we're already using it in the dev-onboarding branch) and trust the cert as necessary either post-up or post-provision.

From what I've found online, it's not really possible to interactively enter your password on a per-host basis (guest and local in this case). Let me know if you happen to have found anything different or if the above doesn't sound like the correct approach.

**Comment by likeuntomurphy** [comment]
For the record, the above does prompt for a password and works:

<img width="1047" alt="screen shot 2017-11-25 at 3 26 46 pm" src="https://user-images.githubusercontent.com/2012253/33234458-2f065786-d1f5-11e7-9aa1-a21d1def93c3.png">
