### ISSUE TITLE
Change TLD

### ISSUE THREAD

**Issue by likeuntomurphy** [fostermadeco/development-standard#6]
Do we relent in the face of Google and change `.dev` to something else? We already have to change it for Mailhog to be accessible.

**Comment by adam-winfree** [comment]
(Only commenting because this has been annoying me) We don't really have a choice, do we? Reserved .example and .test work, and we don't really use either for their 'intended' use.

**Comment by gstjohn** [comment]
Ultimately, I want to leave that up to you, @likeuntomurphy and @alexmglover. For the dev work I have done lately, I yelled "Get off my lawn" in Google's general direction and then bit the bullet. It's made the whole devops process easier from my perspective by not having to fight the system.

**Comment by likeuntomurphy** [comment]
@adam-winfree There are older projects that have not yet included the update that automatically trusts the self-signed cert. For any new projects that do, you can continue to use .dev in Chrome without any problems. 

The one obstacle is Mailhog — but we can add `domain.email` as a hostsupdater alias and continue to access the site as `domain.dev` and Mailhog as `domain.email:8025`.

`.example`, `local` and `localhost` are too long. `.test` is inaccurate.

**Comment by alexmglover** [comment]
I noticed that Laravel’s valet changed the default to .test. I think change is inevitable.

Piggybacking on what Jonathan said, you shouldn't have any issues with this working with our Vagrant box. The certs are trusted automatically, and if they aren't then you should update your ansible scripts to use the latest version. The CMS team is currently using our vagrant box with a `.dev` domain for multiple projects with no issues.

Our solution for the Mailhog problem is to hit `ip-of-box:8025`.

**Comment by alexmglover** [comment]
I noticed that Laravel’s valet changed the default to .test. I think change is inevitable.

**Comment by gstjohn** [comment]
I'm comfortable landing on whatever this group chooses, but at that point, it will be important to make the announcement to the team and get existing project/ansible scripts updated so there is less guessing.

Submit your vote: https://goo.gl/forms/Gut9Pl1YzX8VLX7z2

**Comment by likeuntomurphy** [comment]
How about `.fm`?

**Comment by gstjohn** [comment]
Now you're talking...

**Comment by kellypacker** [comment]
I like `.fm`, but would it make it more difficult or weird when we are working with another company or when we hand a project off to another company? In theory local env variables aren't tracked in git, but seems like sometimes defaults are included or for some reason they end up in there on occasion. I'm thinking about VSA and the PWA. Obviously they can be altered so it's probably not a deal breaker.

**Comment by adam-winfree** [comment]
https://en.wikipedia.org/wiki/.fm

**Comment by likeuntomurphy** [comment]
@kellypacker I wouldn't be too concerned about what happens if we were to hand a project over to another company. They could 1) use a local provisioner of their choosing, or 2) change the hostname in the `group_vars/all` file to one of their choosing.

**Comment by gstjohn** [comment]
It looks like we landed on staying with .dev. What needs to happen to get this working across all project VMs?

**Comment by smaida** [comment]
My preference would be to move away from .dev. I find development with the TLD to be rather cumbersome across the shop and I would like something that isn't particularly difficult for the CMS side of the house. 

My limited reading suggests that .test is the recommendation. Here is one article:
https://medium.engineering/use-a-dev-domain-not-anymore-95219778e6fd

**Comment by gstjohn** [comment]
I would tend to agree despite `.test` just not sitting overly right with me semantically. It's important for us to keep the technical overhead low for getting an environment up and running. It also sounds like `.test` is reserved so we shouldn't come up against this issue again since Google or others don't own the TLD.

Any final thoughts before we commit to moving forward with `.test` across the shop?

**Comment by likeuntomurphy** [comment]
Here are my final thoughts.

I think it’s important to step back and understand what “problem” we’re trying to address. I actually hesitate to call it a “problem” — more like ”complications” that Google has put in the path of every web developer. These are what are laid out in the post provided by @smaida — but it is important to emphasize that these obstacles are not insurmountable.

There are only two: 1) Chrome put `.dev` sites in its HSTS preload list, meaning the sites have to be served exclusively over SSL; 2) the SSL certificates for `.dev` sites need to be valid and trusted.

The solution should be clear: It’s not to abandon using `.dev` as the TLD for local development, it’s to make sure the site is only served with SSL and to make sure that your host system trusts the certificate. That’s it. Both of these tasks are part of the current provisioning process — the first always has been, and the second is a more recent enhancement.

Were we to switch to `.test` or something else, we would still have already addressed both of these obstacles, and it will have been an unnecessary change.

But if there are lingering issues related to the TLD, then the solution is to do what we have already discussed and make sure that the provisioner in each project is up to date and automatically trusts the self-signed cert.

Now I know I am the one who initially created this issue for discussion, but I must say that upon further reflection I’ve decided that opting for a different TLD simply because Google _forced_ us to use SSL and trusted certificates seems either arbitrary at best or lazy at worst.

Lastly, we should encourage anyone who encounters any other problems to discuss them openly with the team or create issues here. The majority of problems encountered have been due to dependencies that were added to a project but not the provisioner. Legitimate bugs can and should be fixed.

**Comment by smaida** [comment]
@likeuntomurphy Thank you. I understand what you're saying here and perhaps I'm conflating concerns.

I agree with your comments; however, I'm not convinced that .dev is the best route even if I agree with many of the points in your comment.

Years ago the majority of sites we worked on used .local as the TLD. That was true of our own projects and those from our clients. If I remember correctly, we switched to .dev because Lion took 4-5 seconds to resolve DNS for .local.

Two questions. Is there value in using a reserved TLD for development or is that not a concern? Is the industry making a shift away from .dev?

**Comment by likeuntomurphy** [comment]
I too used to use `.local`, until  1) either Safari or Chrome would frequently not recognize it as a TLD and would issue a Google search instead; 2) I started using Puphpet regularly, which always used `awesome.dev` as the default hostname.

The only reason I can see to use a reserved TLD is to ensure that whatever local domain names we use never conflict with publicly registered names. That’s the express rationale behind their existence — to reduce “confusion and conflict.” Personally I believe the possibility that we will encounter conflicts during development is low — 1) Google will have to actually begin selling `.dev` names, which they haven’t yet and perhaps never will (there are conflicting reports);  2) entities will have to register names that exactly match the ones we use for our (comparatively small) client base. I think we understand this risk and chose to continue using `.dev` nonetheless.

If there is a shift away from `.dev` I believe it is overwhelmingly due to Chicken Little hysteria that Google “took `.dev` away from us,” with “+1s” and “works for me” indicating most will accept whatever’s easiest. The Medium engineering article may be one of the few that lay out both paths forward with an actual argument for moving to `.test`, but I find the argument pretty thin without any discussion of any other complications that a gTLD owner can put in your way.

Ultimately, Google did not make changes that require `.dev` domains to be handled differently from others — it’s just that other gTLD owners haven’t made the same requirements. That actually means that using `.dev` demands more of us as programmers and makes our local environments adequate to a greater number of production possibilities. One of the aims of this project was to ensure that we were creating secure web environments from the ground up, and we cannot but do so when using `.dev`.

**Comment by gstjohn** [comment]
I think everyone has made valid points here and it's time to move forward. I'm comfortable going with `.dev` as long as @alexmglover is too. She'll be handling the bulk of issues that may arise with the CMS team.

Assuming all is good...

- What is the effort involved with getting all active projects set up for `.dev` and using a trusted self-signed cert? Will people need to rebuild their VMs?
- What, if any, issues need to be handled for Mailhog?
- How can we convey this change to the team to lower their down time?
- Who will commit to documenting the set up process in the [Standards Repo](https://github.com/fostermadeco/development-standard/)?

**Comment by smaida** [comment]
We have our first Vagrant training session with the CMS team next week. We have work to do on the CMS team to bring everyone up to speed, but we'll get there.

**Comment by likeuntomurphy** [comment]
I created pull requests to add a virtual host that serves as a reverse proxy for Mailhog. The email domain defaults to `{{ 'email.' ~ hostname }}` when no `email_hostname` is defined in the vars file.

When merged, Mailhog will be available at https://email.example.dev instead of http://example.dev:8025.

It will be incorporated into all projects as `roles` and the Vagrantfile/vars are updated in each.
